import type { UserRole } from './types';
import {
  LayoutDashboard,
  Book,
  Calendar,
  BarChart,
  Trophy,
  Link,
  FileText,
  Shield,
  Focus,
  Users,
  MessageSquare,
  ClipboardList,
  UserCheck,
  LineChart,
  Frown,
  BrainCircuit,
  Bell,
  UserPlus,
  QrCode,
  FolderArchive,
} from 'lucide-react';

export const navLinks: Record<
  UserRole,
  { title: string; href: string; icon: React.ElementType }[]
> = {
  student: [
    { title: 'Dashboard', href: '/student', icon: LayoutDashboard },
    { title: 'AI Focus Mode', href: '/student/focus-mode', icon: Focus },
    { title: 'Join Class', href: '/student/join-class', icon: UserPlus },
    { title: 'Homework', href: '/student/homework', icon: Book },
    { title: 'My Vault', href: '/student/vault', icon: FolderArchive },
    { title: 'Calendar', href: '/student/calendar', icon: Calendar },
    { title: 'Leaderboard', href: '/student/ranking', icon: Trophy },
    { title: 'Study Links', href: '/student/study-links', icon: Link },
    { title: 'Exams', href: '/student/exams', icon: FileText },
    { title: 'Achievements', href: '/student/gamification', icon: Shield },
    { title: 'Notifications', href: '/student/notifications', icon: Bell },
  ],
  parent: [
    { title: 'Dashboard', href: '/parent', icon: LayoutDashboard },
    { title: 'Child Analytics', href: '/parent/analytics', icon: LineChart },
    { title: 'Complaint Portal', href: '/parent/complaints', icon: Frown },
    { title: 'Homework Tracking', href: '/parent/homework', icon: ClipboardList },
    { title: 'Behaviour Insights', href: '/parent/behavior-insights', icon: BrainCircuit },
    { title: 'Calendar Access', href: '/parent/calendar', icon: Calendar },
    { title: 'Notifications', href: '/parent/notifications', icon: Bell },
  ],
  teacher: [
    { title: 'Dashboard', href: '/teacher', icon: LayoutDashboard },
    { title: 'Analytics', href: '/teacher/analytics', icon: BarChart },
    { title: 'Join Class', href: '/teacher/join-class', icon: UserPlus },
    { title: 'Complaints', href: '/teacher/complaints', icon: Frown },
    { title: 'Homework', href: '/teacher/homework', icon: Book },
    { title: 'Student Ranking', href: '/teacher/ranking', icon: Trophy },
    { title: 'Behaviour Mgt.', href: '/teacher/behavior-management', icon: UserCheck },
    { title: 'Notifications', href: '/teacher/notifications', icon: Bell },
  ],
  admin: [
    { title: 'Dashboard', href: '/admin', icon: LayoutDashboard },
    { title: 'User Management', href: '/admin/user-management', icon: Users },
    { title: 'Class Codes', href: '/admin/class-codes', icon: QrCode },
    { title: 'Communication Hub', href: '/admin/communication-hub', icon: MessageSquare },
    { title: 'Calendar Mgt.', href: '/admin/calendar-management', icon: Calendar },
    { title: 'Notifications', href: '/admin/notifications', icon: Bell },
  ],
};